name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        
    - name: Setup environment
      run: |
        python -m pip install uv
        uv venv
        uv pip install ".[dev]"
        uv pip install black isort ruff
        uv pip install pytest-asyncio pytest-cov
        
    - name: Verify formatting and linting
      run: |
        uv run black --check .
        uv run isort --check .
        uv run ruff check .
        
    - name: Run tests with coverage
      run: |
        PYTHONPATH=. uv run pytest -xvs --cov=. --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 